# -*- coding: utf-8 -*-
"""Build one product's app file from sarathi_biz.py by REMOVING the other product's code.

    py -3.13 deploy/extract-app.py             -> nidaan_app.py
    py -3.13 deploy/extract-app.py --sarathi   -> sarathi_app.py

The tempting build is additive: collect one product's routes and helpers and assemble a new file
from them. That requires being right about every dependency, and anything missed is a NameError
at some call site weeks later, on a path nobody exercised.

So this is SUBTRACTIVE. Start from a byte-for-byte copy of the file that works today and delete
only the top-level definitions that provably belong to the other product. Source order is
untouched, so every definition still precedes its use and every module-level side effect still
happens in the same order it does now.

AND IT CHECKS ITS OWN WORK. Both directions have already produced the same class of failure - a
name dropped as the other product's that some kept code still refers to. SERVER_URL and
SERVER_PORT leaving the Nidaan build; _doc_access_ok leaving the Sarathi one. Both were found by
pyflakes and both times the rule was fixed by hand, which does not scale: routes registered in a
LOOP are invisible to the classifier, so there will always be a reference the analysis cannot
see.

So it builds, asks what is undefined, puts those definitions back, and builds again - until
nothing is undefined. A build that cannot reach zero writes nothing.

sarathi_biz.py is never modified.
"""
import ast
import io
import json
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "sarathi_biz.py")
SURFACE = os.path.join(ROOT, "deploy", "split-surface.json")

KEEP = "sarathi" if "--sarathi" in sys.argv else "nidaan"
OTHER = "nidaan" if KEEP == "sarathi" else "sarathi"
OUT = os.path.join(ROOT, "%s_app.py" % KEEP)

HEADER = (
    "# -*- coding: utf-8 -*-\n"
    "# %s - the application, on its own.\n"
    "#\n"
    "# Generated by deploy/extract-app.py, SUBTRACTIVELY: a copy of sarathi_biz.py with only\n"
    "# the provably %s-only definitions removed. Source order is untouched, so every\n"
    "# definition still precedes its use and every module-level side effect still happens in\n"
    "# the order it always did.\n"
    "#\n"
    "# Do not hand-edit while the split is in progress - re-run the extractor.\n"
    % ("NidaanPartner.com" if KEEP == "nidaan" else "Sarathi-AI.com", OTHER))


def undefined_names(text: str) -> set:
    """What does this build refer to that it no longer defines?

    pyflakes, not a scope walker of my own: it already understands comprehensions, globals,
    nested functions and every other way a name gets bound, and getting that subtly wrong is
    how a checker quietly passes a broken build.
    """
    fd, tmp = tempfile.mkstemp(suffix=".py")
    os.close(fd)
    try:
        io.open(tmp, "w", encoding="utf-8", newline="").write(text)
        r = subprocess.run([sys.executable, "-m", "pyflakes", tmp],
                           capture_output=True, text=True)
        out = set()
        for line in (r.stdout or "").splitlines():
            if "undefined name" in line:
                out.add(line.rsplit("undefined name", 1)[1].strip().strip("'\""))
        return out
    finally:
        try:
            os.unlink(tmp)
        except Exception:
            pass


def build(lines, tree, drop_names):
    """One pass: remove those top-level definitions, keep everything else exactly as it was."""
    spans, dropped = [], []
    for n in tree.body:
        # ONLY functions and classes are ever dropped. Module-level constants stay, always -
        # the first Nidaan build dropped SERVER_URL and SERVER_PORT and produced twelve
        # undefined names. A constant costs bytes to keep and a NameError to drop.
        if not isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            continue
        if n.name not in drop_names:
            continue
        start = min([n.lineno] + [d.lineno for d in getattr(n, "decorator_list", [])])
        i = start - 2
        while i >= 0 and (lines[i].lstrip().startswith("#") or not lines[i].strip()):
            if lines[i].strip() and not lines[i].lstrip().startswith("#"):
                break
            i -= 1
        spans.append((i + 2, n.end_lineno))
        dropped.append(n.name)

    spans.sort()
    merged = []
    for a, b in spans:
        if merged and a <= merged[-1][1] + 1:
            merged[-1] = (merged[-1][0], max(merged[-1][1], b))
        else:
            merged.append((a, b))
    cut = set()
    for a, b in merged:
        cut |= set(range(a, b + 1))
    keep = [ln for i, ln in enumerate(lines, 1) if i not in cut]
    return HEADER + "\n".join(keep), dropped


def main() -> int:
    src = io.open(SRC, encoding="utf-8").read()
    lines = src.split("\n")
    tree = ast.parse(src)
    surface = json.loads(io.open(SURFACE, encoding="utf-8").read())

    drop_routes = {r["func"] for r in surface["routes"] if r["product"] == OTHER}
    keep_routes = {r["func"] for r in surface["routes"] if r["product"] == KEEP}
    shared_routes = {r["func"] for r in surface["routes"] if r["product"] == "shared"}

    protected = set(keep_routes) | set(shared_routes)
    for r in surface["routes"]:
        if r["product"] in (KEEP, "shared"):
            protected |= set(r["reaches"])

    drop_names = (drop_routes | set(surface["only_%s" % OTHER])) - protected

    out = dropped = None
    for _ in range(8):
        out, dropped = build(lines, tree, drop_names)
        missing = undefined_names(out)
        if not missing:
            break
        restore = missing & drop_names
        if not restore:
            print("!! undefined after repair, and none were dropped by me: %s"
                  % ", ".join(sorted(missing)[:8]))
            print("   nothing written")
            return 1
        print("  putting back %d name(s) the analysis could not see were used: %s"
              % (len(restore), ", ".join(sorted(restore)[:6])))
        drop_names -= restore
    else:
        print("!! could not reach a build with zero undefined names - nothing written")
        return 1

    try:
        newtree = ast.parse(out)
    except SyntaxError as e:
        print("!! the result does not parse: line %s: %s - nothing written" % (e.lineno, e.msg))
        return 1

    got = set()
    for n in ast.walk(newtree):
        if isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)):
            for d in n.decorator_list:
                if (isinstance(d, ast.Call) and isinstance(d.func, ast.Attribute)
                        and isinstance(d.func.value, ast.Name) and d.func.value.id == "app"):
                    got.add(n.name)
    lost = sorted((keep_routes | shared_routes) - got)
    if lost:
        print("!! %d %s/shared route(s) did not survive: %s - nothing written"
              % (len(lost), KEEP, lost[:8]))
        return 1

    io.open(OUT, "w", encoding="utf-8", newline="").write(out)
    kept_lines = out.count("\n") + 1
    print("\n%s written\n" % os.path.basename(OUT))
    print("  lines  : %d  ->  %d" % (len(lines), kept_lines))
    print("  dropped: %d %s-only definitions" % (len(dropped), OTHER))
    print("  kept   : every one of the %d %s and %d shared routes"
          % (len(keep_routes), KEEP, len(shared_routes)))
    print("  undefined names: 0 - checked, and repaired where the analysis was blind")
    print("\n  sarathi_biz.py was NOT modified.")
    return 0


sys.exit(main())
