#!/usr/bin/env bash
# =============================================================================
#  Server-side limits for 95 MB documents (founder, 3 Oct 2026: "100 MB each")
# =============================================================================
#  The app's own limit lives in biz_nidaan_limits.py. Two things outside the app
#  must sit ABOVE it, or a file the app would accept is refused before it gets
#  there - with an unhelpful error the person cannot act on:
#
#   * nginx  client_max_body_size  50M -> 100M   (one request = one file + form;
#            Cloudflare caps a request at 100 MB, so 100M is the honest ceiling)
#   * clamd  StreamMaxLength / MaxFileSize  64M -> 110M  (a file the scanner
#            cannot finish is REFUSED by the app - it never waves one through)
#
#  clamd.conf is generated by the clamav-daemon package from debconf, so the
#  stream limit is set in debconf too; otherwise a package upgrade would quietly
#  put 64M back and big uploads would start failing. After any clamav upgrade,
#  run `status` - it says if anything has drifted.
#
#  USAGE
#    sudo bash deploy/server-upload-limits.sh apply
#    sudo bash deploy/server-upload-limits.sh status
#    sudo bash deploy/server-upload-limits.sh undo
# =============================================================================
set -euo pipefail

ACTION="${1:-status}"
SITE="/etc/nginx/sites-enabled/sarathi"
CLAMD="/etc/clamav/clamd.conf"
NGINX_NEW="100M"; NGINX_OLD="50M"
CLAM_NEW="110M"; CLAM_OLD="64M"
SOCK="/var/run/clamav/clamd.ctl"
STAMP=$(date +%Y%m%d_%H%M%S)
# Backups live OUTSIDE sites-enabled: nginx loads every file in that folder.
BAK_DIR="/etc/nginx/backup-sarathi"

[[ $EUID -ne 0 ]] && { echo "Run with sudo."; exit 1; }

clamd_ping() {
  for _ in $(seq 1 60); do
    if python3 - "$SOCK" <<'PY' 2>/dev/null
import socket, sys
s = socket.socket(socket.AF_UNIX); s.settimeout(3); s.connect(sys.argv[1])
s.sendall(b"zPING\0"); ok = s.recv(16).startswith(b"PONG"); s.close()
sys.exit(0 if ok else 1)
PY
    then return 0; fi
    sleep 2
  done
  return 1
}

status() {
  echo "nginx:  $(grep -c "client_max_body_size $NGINX_NEW;" "$SITE") of $(grep -c 'client_max_body_size' "$SITE") server blocks at $NGINX_NEW"
  grep -n 'client_max_body_size' "$SITE" | sed 's/^/        /'
  echo "clamd:  $(grep -E '^(StreamMaxLength|MaxFileSize|MaxScanSize) ' "$CLAMD" | tr '\n' ' ')"
  echo "debconf StreamMaxLength: $(debconf-show clamav-daemon 2>/dev/null | awk -F': ' '/StreamMaxLength/{print $2}')"
  clamd_ping && echo "clamd answers: yes" || echo "*** clamd does not answer ***"
}

apply() {
  mkdir -p "$BAK_DIR"
  # ── the scanner first: the app must never accept what the scanner cannot finish ──
  cp -p "$CLAMD" "$CLAMD.bak-$STAMP"
  sed -i -E "s/^StreamMaxLength .*/StreamMaxLength $CLAM_NEW/; s/^MaxFileSize .*/MaxFileSize $CLAM_NEW/" "$CLAMD"
  grep -q "^StreamMaxLength $CLAM_NEW$" "$CLAMD" && grep -q "^MaxFileSize $CLAM_NEW$" "$CLAMD" \
    || { echo "clamd.conf did not take the change - restoring."; cp -p "$CLAMD.bak-$STAMP" "$CLAMD"; exit 1; }
  echo "clamav-daemon clamav-daemon/StreamMaxLength string ${CLAM_NEW%M}" | debconf-set-selections
  systemctl restart clamav-daemon
  if ! clamd_ping; then
    echo "clamd did not come back - restoring the old settings."
    cp -p "$CLAMD.bak-$STAMP" "$CLAMD"
    echo "clamav-daemon clamav-daemon/StreamMaxLength string ${CLAM_OLD%M}" | debconf-set-selections
    systemctl restart clamav-daemon; clamd_ping || echo "*** clamd still not answering - CHECK NOW: uploads are refused while it is down ***"
    exit 1
  fi
  echo "clamd: $CLAM_NEW, answering."

  # ── nginx ──
  cp -p "$SITE" "$BAK_DIR/sarathi.$STAMP"
  sed -i "s/client_max_body_size $NGINX_OLD;/client_max_body_size $NGINX_NEW;/" "$SITE"
  if ! nginx -t 2>&1; then
    echo "nginx refused it - restoring."; cp -p "$BAK_DIR/sarathi.$STAMP" "$SITE"; nginx -t; exit 1
  fi
  systemctl reload nginx
  echo "nginx: $NGINX_NEW, reloaded."
  status
}

undo() {
  sed -i "s/client_max_body_size $NGINX_NEW;/client_max_body_size $NGINX_OLD;/" "$SITE"
  nginx -t && systemctl reload nginx
  sed -i -E "s/^StreamMaxLength .*/StreamMaxLength $CLAM_OLD/; s/^MaxFileSize .*/MaxFileSize $CLAM_OLD/" "$CLAMD"
  echo "clamav-daemon clamav-daemon/StreamMaxLength string ${CLAM_OLD%M}" | debconf-set-selections
  systemctl restart clamav-daemon; clamd_ping || echo "*** clamd not answering ***"
  echo "Back to nginx $NGINX_OLD, clamd $CLAM_OLD. The app's own limit must come down too (biz_nidaan_limits.py)."
  status
}

case "$ACTION" in
  apply)  apply ;;
  undo)   undo ;;
  status) status ;;
  *) echo "Usage: sudo bash $0 {apply|status|undo}"; exit 1 ;;
esac
